/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GeneralDataCore;

import org.junit.Test;

public class LibraryTest {
	
	
	
	
    @Test 
    public void testSomeLibraryMethod() {

    	System.out.println("≤‚ ‘");
    	
    	
    	
    	
    }
    
    
    
    
}
